/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#404752",
        "on-surface-variant": "#c0c7d4",
        "surface-container-lowest": "#090f15",
        "on-tertiary-container": "#4f3000",
        "inverse-primary": "#0060a9",
        "on-secondary-fixed": "#001c38",
        "on-primary-container": "#003866",
        "inverse-on-surface": "#2b3138",
        "error-container": "#93000a",
        "surface-container-high": "#252a31",
        "surface": "#0e141a",
        "surface-variant": "#2f353c",
        "on-background": "#dde3ec",
        "tertiary": "#ffb95c",
        "on-primary": "#00315b",
        "secondary-fixed-dim": "#adc8f1",
        "on-primary-fixed": "#001c38",
        "on-tertiary": "#462a00",
        "secondary": "#adc8f1",
        "on-tertiary-fixed": "#2a1700",
        "tertiary-fixed-dim": "#ffb95c",
        "primary-fixed": "#d3e4ff",
        "on-primary-fixed-variant": "#004881",
        "outline": "#8a919d",
        "secondary-container": "#2c486a",
        "surface-container-highest": "#2f353c",
        "surface-container-low": "#161c23",
        "error": "#ffb4ab",
        "tertiary-container": "#de8f00",
        "background": "#0e141a",
        "surface-bright": "#343a41",
        "on-surface": "#dde3ec",
        "on-error": "#690005",
        "tertiary-fixed": "#ffddb7",
        "on-secondary": "#133252",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#a2c9ff",
        "primary": "#a2c9ff",
        "inverse-surface": "#dde3ec",
        "surface-dim": "#0e141a",
        "surface-container": "#1a2027",
        "secondary-fixed": "#d3e4ff",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-tint": "#a2c9ff",
        "on-secondary-fixed-variant": "#2c486a",
        "on-secondary-container": "#9bb7de",
        "primary-container": "#4da3ff"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
